import { MediaMatcher } from '@angular/cdk/layout';
import { ChangeDetectorRef, ComponentFactoryResolver, ViewContainerRef } from '@angular/core';
import { PxtContentBody } from '../../directives/pxt-content-body';
import { MatMenu, MatMenuTrigger } from '@angular/material';
import { SafeHtml } from '@angular/platform-browser';
import { Observable } from 'rxjs';
import { UserService } from '../../services/user.service';
import { HttpHelperService } from '../../services/pxt-http/http-helper-service';
export declare class PxtAppComponent {
    componentFactoryResolver: ComponentFactoryResolver;
    pxtAppComponentService: any;
    private userService;
    private httpHelperService;
    routes: any[];
    groups: any[];
    menus: any[];
    system: String;
    urlImg: string;
    menuSelected: string;
    usuerLogged: any;
    menusHtml: SafeHtml;
    result: Observable<boolean>;
    _mobileQueryListener: () => void;
    mobileQuery: MediaQueryList;
    shouldRun: boolean;
    matMenu: MatMenu;
    subContainer1: ViewContainerRef;
    contextMenuTrigger: MatMenuTrigger;
    currentAdIndex: number;
    adHost: PxtContentBody;
    interval: any;
    menusReceived: any[];
    urlLogo: string;
    constructor(changeDetectorRef: ChangeDetectorRef, media: MediaMatcher, componentFactoryResolver: ComponentFactoryResolver, pxtAppComponentService: any, userService: UserService, httpHelperService: HttpHelperService);
    ngOnDestroy(): void;
    ngOnInit(): void;
    loadComponent(route: any, adHost: any): void;
    subscribeComponent(): void;
    selectItemMenu(nav: any): void;
    prepareMenu(): void;
    logout(): void;
    findUserLogged(): void;
}
